### ISSUE TITLE
Non-Capturing Parenset not matching

### ISSUE THREAD

**Issue by thenomain** [lashtear/tinymux#1]
`&CMD.LAIR.NOTES #14800=$^\.lair/notes? ([^=]+)(=(\+)?((?:\s|.)*))?$:@assert isstaff( %# )={ @pemit  %#=[ansi( hr, LAIR: )] Staff Only. }; @pemit %#=iter( lnum( 1, 5 ), %i0: [v( %i0 )], , %b--%b )`

```
> .lair/notes 77= %xh%xcThis is a test%xn%rWheez
Huh?  (Type “help” for help.)

> @version
MUX 2.12.0.1 #5 [ALPHA]
Build date: Mon Jul  7 19:56:15 PDT 2014
```

**Comment by thenomain** [comment]
Important addition: It works fine without the `?:`, leaving the match: `(\s|.)*`

**Comment by lashtear** [comment]
Simpler test-cases are love.  This appears to be two issues; after the recent PCRE update upstream by @BrazilOfMux (and maybe before?) the non-capturing parens `(?:foo)` aren't working.  Secondly, there needs to be a better way to specify regex modifiers so that ridiculous things like `(\s|.)` are not needed.  Will look closer, but I could have sworn this all worked before.  (Time for proper regression tests!)

**Comment by brazilofmux** [comment]
@set me=COMMANDS
Set.
&CMD.FOO me=$^.foo/bar? ([^=]+)(=(+)?((?:\s|.)_))?$:@pemit me=Success.
Set.
@set me/CMD.FOO=REGEX
Set.
.foo/bar 123= %xh%xcThis is a test%xn%rWheez
Huh?  (Type "help" for help.)
CMD.FOO me=$^.foo/bar? ([^=]+)(=(+)?((\s|.)_))?$:@pemit me=Success.
Set.
.foo/bar 123= %xh%xcThis is a test%xn%rWheez
Success.
ver
MUX 2.6.5.33 #1 [2012-APR-21]
Build date: Wed Aug 13 12:44:09 MDT 2014

Whatever this is, it has been that way back to 2006. I'll try it further back, but I don't remember PCRE changing much.

**Comment by brazilofmux** [comment]
Same behavior on:

MUX 2.2.15.76 # [2004-DEC-25]
Build date: Wed Aug 13 12:51:20 MDT 2014

**Comment by lashtear** [comment]
Thanks for looking!  Assuming that your `(+)` is `(\+)` where the backslash got eaten, your `(?:\s|.)` is only looking at the first character.  This does suggest that `(?:...)` works, though.  Theno, please retest if I don't get to it tonight?  The `(\s|.)` issue in general should be a separate issue, as I mentioned.  Making PCRE tolerate `%r` is easy enough, but making color coding invisible to it may take some finagling.

**Comment by lashtear** [comment]
Gave this another look-see.  Color matching works fine.  Non-capturing parens work fine.  What doesn't work is using `(?s)` to enable PCRE_DOTALL, so that `.` will match on raw `%r`s.  Theno, reopen if that is still interesting to you.

**Comment by thenomain** [comment]
Using `(?s)` as a precondition has solved many problems with accepting formatted text in a regexp input that I'd rather it be in than dropped. 

I'm using this to wean people off the starting '+' on softcoded commands, so each command is something along the format of: `(?s)^\+?command(.*)$`
