### ISSUE TITLE
@restart crashes the game

### ISSUE THREAD

**Issue by nivthefox** [lashtear/tinymux#3]
Title says it all. Works with a completely fresh install.

"the assertion is checking lt_dlexit() returns cleanly, which... it isn't." - @lashtear

**Comment by lashtear** [comment]
Try now.  That wasn't the right assertion; we had a simple exec to a nonexistent file because I moved netmux et all to libexec.  A proper fix will make those more reconfigurable, but this should work for the moment.  See 953b219.
