### ISSUE TITLE
(?s) precondition not working for %r

### ISSUE THREAD

**Issue by lashtear** [lashtear/tinymux#4]
@Thenomain says:  Using (?s) as a precondition has solved many problems with accepting formatted text in a regexp input that I'd rather it be in than dropped.

I'm using this to wean people off the starting '+' on softcoded commands, so each command is something along the format of: (?s)^+?command(.*)$

---

Formerly issue #1 .  Pulling this out into a separate ticket for saner tracking.

**Comment by lashtear** [comment]
Fixed in a7d679c

**Comment by lashtear** [comment]
Seems working now; please test on your end.

**Comment by thenomain** [comment]
Looks like it's working:

```
&TEST #2=$(?s)^\+?test(.*)$:@pemit %#=TEST ::%r[trim( %1 )] 

Wizard types -=> Test > ds [ansi(y, yes)]%r> %r> Also yes.
TEST ::
> ds yes
> 
> Also yes.
```
